<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countryCodes = [
            ['country_name' => 'Afghanistan', 'country_code' => '+93', 'iso_code' => 'AF'],
            ['country_name' => 'Albania', 'country_code' => '+355', 'iso_code' => 'AL'],
            ['country_name' => 'Algeria', 'country_code' => '+213', 'iso_code' => 'DZ'],
            ['country_name' => 'Andorra', 'country_code' => '+376', 'iso_code' => 'AD'],
            ['country_name' => 'Angola', 'country_code' => '+244', 'iso_code' => 'AO'],
            ['country_name' => 'Argentina', 'country_code' => '+54', 'iso_code' => 'AR'],
            ['country_name' => 'Armenia', 'country_code' => '+374', 'iso_code' => 'AM'],
            ['country_name' => 'Australia', 'country_code' => '+61', 'iso_code' => 'AU'],
            ['country_name' => 'Austria', 'country_code' => '+43', 'iso_code' => 'AT'],
            ['country_name' => 'Azerbaijan', 'country_code' => '+994', 'iso_code' => 'AZ'],
            ['country_name' => 'Bahamas', 'country_code' => '+1-242', 'iso_code' => 'BS'],
            ['country_name' => 'Bahrain', 'country_code' => '+973', 'iso_code' => 'BH'],
            ['country_name' => 'Bangladesh', 'country_code' => '+880', 'iso_code' => 'BD'],
            ['country_name' => 'Barbados', 'country_code' => '+1-246', 'iso_code' => 'BB'],
            ['country_name' => 'Belarus', 'country_code' => '+375', 'iso_code' => 'BY'],
            ['country_name' => 'Belgium', 'country_code' => '+32', 'iso_code' => 'BE'],
            ['country_name' => 'Belize', 'country_code' => '+501', 'iso_code' => 'BZ'],
            ['country_name' => 'Benin', 'country_code' => '+229', 'iso_code' => 'BJ'],
            ['country_name' => 'Bhutan', 'country_code' => '+975', 'iso_code' => 'BT'],
            ['country_name' => 'Bolivia', 'country_code' => '+591', 'iso_code' => 'BO'],
            ['country_name' => 'Bosnia and Herzegovina', 'country_code' => '+387', 'iso_code' => 'BA'],
            ['country_name' => 'Botswana', 'country_code' => '+267', 'iso_code' => 'BW'],
            ['country_name' => 'Brazil', 'country_code' => '+55', 'iso_code' => 'BR'],
            ['country_name' => 'Brunei', 'country_code' => '+673', 'iso_code' => 'BN'],
            ['country_name' => 'Bulgaria', 'country_code' => '+359', 'iso_code' => 'BG'],
            ['country_name' => 'Burkina Faso', 'country_code' => '+226', 'iso_code' => 'BF'],
            ['country_name' => 'Burundi', 'country_code' => '+257', 'iso_code' => 'BI'],
            ['country_name' => 'Cambodia', 'country_code' => '+855', 'iso_code' => 'KH'],
            ['country_name' => 'Cameroon', 'country_code' => '+237', 'iso_code' => 'CM'],
            ['country_name' => 'Canada', 'country_code' => '+1', 'iso_code' => 'CA'],
            ['country_name' => 'Cape Verde', 'country_code' => '+238', 'iso_code' => 'CV'],
            ['country_name' => 'Central African Republic', 'country_code' => '+236', 'iso_code' => 'CF'],
            ['country_name' => 'Chad', 'country_code' => '+235', 'iso_code' => 'TD'],
            ['country_name' => 'Chile', 'country_code' => '+56', 'iso_code' => 'CL'],
            ['country_name' => 'China', 'country_code' => '+86', 'iso_code' => 'CN'],
            ['country_name' => 'Colombia', 'country_code' => '+57', 'iso_code' => 'CO'],
            ['country_name' => 'Comoros', 'country_code' => '+269', 'iso_code' => 'KM'],
            ['country_name' => 'Congo', 'country_code' => '+242', 'iso_code' => 'CG'],
            ['country_name' => 'Congo (DRC)', 'country_code' => '+243', 'iso_code' => 'CD'],
            ['country_name' => 'Costa Rica', 'country_code' => '+506', 'iso_code' => 'CR'],
            ['country_name' => 'Croatia', 'country_code' => '+385', 'iso_code' => 'HR'],
            ['country_name' => 'Cuba', 'country_code' => '+53', 'iso_code' => 'CU'],
            ['country_name' => 'Cyprus', 'country_code' => '+357', 'iso_code' => 'CY'],
            ['country_name' => 'Czech Republic', 'country_code' => '+420', 'iso_code' => 'CZ'],
            ['country_name' => 'Denmark', 'country_code' => '+45', 'iso_code' => 'DK'],
            ['country_name' => 'Djibouti', 'country_code' => '+253', 'iso_code' => 'DJ'],
            ['country_name' => 'Dominica', 'country_code' => '+1-767', 'iso_code' => 'DM'],
            ['country_name' => 'Dominican Republic', 'country_code' => '+1-809', 'iso_code' => 'DO'],
            ['country_name' => 'Ecuador', 'country_code' => '+593', 'iso_code' => 'EC'],
            ['country_name' => 'Egypt', 'country_code' => '+20', 'iso_code' => 'EG'],
            ['country_name' => 'El Salvador', 'country_code' => '+503', 'iso_code' => 'SV'],
            ['country_name' => 'Equatorial Guinea', 'country_code' => '+240', 'iso_code' => 'GQ'],
            ['country_name' => 'Eritrea', 'country_code' => '+291', 'iso_code' => 'ER'],
            ['country_name' => 'Estonia', 'country_code' => '+372', 'iso_code' => 'EE'],
            ['country_name' => 'Eswatini', 'country_code' => '+268', 'iso_code' => 'SZ'],
            ['country_name' => 'Ethiopia', 'country_code' => '+251', 'iso_code' => 'ET'],
            ['country_name' => 'Fiji', 'country_code' => '+679', 'iso_code' => 'FJ'],
            ['country_name' => 'Finland', 'country_code' => '+358', 'iso_code' => 'FI'],
            ['country_name' => 'France', 'country_code' => '+33', 'iso_code' => 'FR'],
            ['country_name' => 'Gabon', 'country_code' => '+241', 'iso_code' => 'GA'],
            ['country_name' => 'Gambia', 'country_code' => '+220', 'iso_code' => 'GM'],
            ['country_name' => 'Georgia', 'country_code' => '+995', 'iso_code' => 'GE'],
            ['country_name' => 'Germany', 'country_code' => '+49', 'iso_code' => 'DE'],
            ['country_name' => 'Ghana', 'country_code' => '+233', 'iso_code' => 'GH'],
            ['country_name' => 'Greece', 'country_code' => '+30', 'iso_code' => 'GR'],
            ['country_name' => 'Greenland', 'country_code' => '+299', 'iso_code' => 'GL'],
            ['country_name' => 'Grenada', 'country_code' => '+1-473', 'iso_code' => 'GD'],
            ['country_name' => 'Guatemala', 'country_code' => '+502', 'iso_code' => 'GT'],
            ['country_name' => 'Guinea', 'country_code' => '+224', 'iso_code' => 'GN'],
            ['country_name' => 'Guinea-Bissau', 'country_code' => '+245', 'iso_code' => 'GW'],
            ['country_name' => 'Guyana', 'country_code' => '+592', 'iso_code' => 'GY'],
            ['country_name' => 'Haiti', 'country_code' => '+509', 'iso_code' => 'HT'],
            ['country_name' => 'Honduras', 'country_code' => '+504', 'iso_code' => 'HN'],
            ['country_name' => 'Hungary', 'country_code' => '+36', 'iso_code' => 'HU'],
            ['country_name' => 'Iceland', 'country_code' => '+354', 'iso_code' => 'IS'],
            ['country_name' => 'India', 'country_code' => '+91', 'iso_code' => 'IN'],
            ['country_name' => 'Indonesia', 'country_code' => '+62', 'iso_code' => 'ID'],
            ['country_name' => 'Iran', 'country_code' => '+98', 'iso_code' => 'IR'],
            ['country_name' => 'Iraq', 'country_code' => '+964', 'iso_code' => 'IQ'],
            ['country_name' => 'Ireland', 'country_code' => '+353', 'iso_code' => 'IE'],
            ['country_name' => 'Israel', 'country_code' => '+972', 'iso_code' => 'IL'],
            ['country_name' => 'Italy', 'country_code' => '+39', 'iso_code' => 'IT'],
            ['country_name' => 'Jamaica', 'country_code' => '+1-876', 'iso_code' => 'JM'],
            ['country_name' => 'Japan', 'country_code' => '+81', 'iso_code' => 'JP'],
            ['country_name' => 'Jordan', 'country_code' => '+962', 'iso_code' => 'JO'],
            ['country_name' => 'Kazakhstan', 'country_code' => '+7', 'iso_code' => 'KZ'],
            ['country_name' => 'Kenya', 'country_code' => '+254', 'iso_code' => 'KE'],
            ['country_name' => 'Kiribati', 'country_code' => '+686', 'iso_code' => 'KI'],
            ['country_name' => 'Korea, North', 'country_code' => '+850', 'iso_code' => 'KP'],
            ['country_name' => 'Korea, South', 'country_code' => '+82', 'iso_code' => 'KR'],
            ['country_name' => 'Kosovo', 'country_code' => '+383', 'iso_code' => 'XK'],
            ['country_name' => 'Kuwait', 'country_code' => '+965', 'iso_code' => 'KW'],
            ['country_name' => 'Kyrgyzstan', 'country_code' => '+996', 'iso_code' => 'KG'],
            ['country_name' => 'Laos', 'country_code' => '+856', 'iso_code' => 'LA'],
            ['country_name' => 'Latvia', 'country_code' => '+371', 'iso_code' => 'LV'],
            ['country_name' => 'Lebanon', 'country_code' => '+961', 'iso_code' => 'LB'],
            ['country_name' => 'Lesotho', 'country_code' => '+266', 'iso_code' => 'LS'],
            ['country_name' => 'Liberia', 'country_code' => '+231', 'iso_code' => 'LR'],
            ['country_name' => 'Libya', 'country_code' => '+218', 'iso_code' => 'LY'],
            ['country_name' => 'Liechtenstein', 'country_code' => '+423', 'iso_code' => 'LI'],
            ['country_name' => 'Lithuania', 'country_code' => '+370', 'iso_code' => 'LT'],
            ['country_name' => 'Luxembourg', 'country_code' => '+352', 'iso_code' => 'LU'],
            ['country_name' => 'Madagascar', 'country_code' => '+261', 'iso_code' => 'MG'],
            ['country_name' => 'Malawi', 'country_code' => '+265', 'iso_code' => 'MW'],
            ['country_name' => 'Malaysia', 'country_code' => '+60', 'iso_code' => 'MY'],
            ['country_name' => 'Maldives', 'country_code' => '+960', 'iso_code' => 'MV'],
            ['country_name' => 'Mali', 'country_code' => '+223', 'iso_code' => 'ML'],
            ['country_name' => 'Malta', 'country_code' => '+356', 'iso_code' => 'MT'],
            ['country_name' => 'Marshall Islands', 'country_code' => '+692', 'iso_code' => 'MH'],
            ['country_name' => 'Mauritania', 'country_code' => '+222', 'iso_code' => 'MR'],
            ['country_name' => 'Mauritius', 'country_code' => '+230', 'iso_code' => 'MU'],
            ['country_name' => 'Mexico', 'country_code' => '+52', 'iso_code' => 'MX'],
            ['country_name' => 'Micronesia', 'country_code' => '+691', 'iso_code' => 'FM'],
            ['country_name' => 'Moldova', 'country_code' => '+373', 'iso_code' => 'MD'],
            ['country_name' => 'Monaco', 'country_code' => '+377', 'iso_code' => 'MC'],
            ['country_name' => 'Mongolia', 'country_code' => '+976', 'iso_code' => 'MN'],
            ['country_name' => 'Montenegro', 'country_code' => '+382', 'iso_code' => 'ME'],
            ['country_name' => 'Morocco', 'country_code' => '+212', 'iso_code' => 'MA'],
            ['country_name' => 'Mozambique', 'country_code' => '+258', 'iso_code' => 'MZ'],
            ['country_name' => 'Myanmar', 'country_code' => '+95', 'iso_code' => 'MM'],
            ['country_name' => 'Namibia', 'country_code' => '+264', 'iso_code' => 'NA'],
            ['country_name' => 'Nauru', 'country_code' => '+674', 'iso_code' => 'NR'],
            ['country_name' => 'Nepal', 'country_code' => '+977', 'iso_code' => 'NP'],
            ['country_name' => 'Netherlands', 'country_code' => '+31', 'iso_code' => 'NL'],
            ['country_name' => 'New Zealand', 'country_code' => '+64', 'iso_code' => 'NZ'],
            ['country_name' => 'Nicaragua', 'country_code' => '+505', 'iso_code' => 'NI'],
            ['country_name' => 'Niger', 'country_code' => '+227', 'iso_code' => 'NE'],
            ['country_name' => 'Nigeria', 'country_code' => '+234', 'iso_code' => 'NG'],
            ['country_name' => 'North Macedonia', 'country_code' => '+389', 'iso_code' => 'MK'],
            ['country_name' => 'Norway', 'country_code' => '+47', 'iso_code' => 'NO'],
            ['country_name' => 'Oman', 'country_code' => '+968', 'iso_code' => 'OM'],
            ['country_name' => 'Pakistan', 'country_code' => '+92', 'iso_code' => 'PK'],
            ['country_name' => 'Palau', 'country_code' => '+680', 'iso_code' => 'PW'],
            ['country_name' => 'Palestine', 'country_code' => '+970', 'iso_code' => 'PS'],
            ['country_name' => 'Panama', 'country_code' => '+507', 'iso_code' => 'PA'],
            ['country_name' => 'Papua New Guinea', 'country_code' => '+675', 'iso_code' => 'PG'],
            ['country_name' => 'Paraguay', 'country_code' => '+595', 'iso_code' => 'PY'],
            ['country_name' => 'Peru', 'country_code' => '+51', 'iso_code' => 'PE'],
            ['country_name' => 'Philippines', 'country_code' => '+63', 'iso_code' => 'PH'],
            ['country_name' => 'Poland', 'country_code' => '+48', 'iso_code' => 'PL'],
            ['country_name' => 'Portugal', 'country_code' => '+351', 'iso_code' => 'PT'],
            ['country_name' => 'Qatar', 'country_code' => '+974', 'iso_code' => 'QA'],
            ['country_name' => 'Romania', 'country_code' => '+40', 'iso_code' => 'RO'],
            ['country_name' => 'Russia', 'country_code' => '+7', 'iso_code' => 'RU'],
            ['country_name' => 'Rwanda', 'country_code' => '+250', 'iso_code' => 'RW'],
            ['country_name' => 'Saint Kitts and Nevis', 'country_code' => '+1-869', 'iso_code' => 'KN'],
            ['country_name' => 'Saint Lucia', 'country_code' => '+1-758', 'iso_code' => 'LC'],
            ['country_name' => 'Saint Vincent and the Grenadines', 'country_code' => '+1-784', 'iso_code' => 'VC'],
            ['country_name' => 'Samoa', 'country_code' => '+685', 'iso_code' => 'WS'],
            ['country_name' => 'San Marino', 'country_code' => '+378', 'iso_code' => 'SM'],
            ['country_name' => 'Saudi Arabia', 'country_code' => '+966', 'iso_code' => 'SA'],
            ['country_name' => 'Senegal', 'country_code' => '+221', 'iso_code' => 'SN'],
            ['country_name' => 'Serbia', 'country_code' => '+381', 'iso_code' => 'RS'],
            ['country_name' => 'Seychelles', 'country_code' => '+248', 'iso_code' => 'SC'],
            ['country_name' => 'Sierra Leone', 'country_code' => '+232', 'iso_code' => 'SL'],
            ['country_name' => 'Singapore', 'country_code' => '+65', 'iso_code' => 'SG'],
            ['country_name' => 'Slovakia', 'country_code' => '+421', 'iso_code' => 'SK'],
            ['country_name' => 'Slovenia', 'country_code' => '+386', 'iso_code' => 'SI'],
            ['country_name' => 'Solomon Islands', 'country_code' => '+677', 'iso_code' => 'SB'],
            ['country_name' => 'Somalia', 'country_code' => '+252', 'iso_code' => 'SO'],
            ['country_name' => 'South Africa', 'country_code' => '+27', 'iso_code' => 'ZA'],
            ['country_name' => 'South Sudan', 'country_code' => '+211', 'iso_code' => 'SS'],
            ['country_name' => 'Spain', 'country_code' => '+34', 'iso_code' => 'ES'],
            ['country_name' => 'Sri Lanka', 'country_code' => '+94', 'iso_code' => 'LK'],
            ['country_name' => 'Sudan', 'country_code' => '+249', 'iso_code' => 'SD'],
            ['country_name' => 'Suriname', 'country_code' => '+597', 'iso_code' => 'SR'],
            ['country_name' => 'Sweden', 'country_code' => '+46', 'iso_code' => 'SE'],
            ['country_name' => 'Switzerland', 'country_code' => '+41', 'iso_code' => 'CH'],
            ['country_name' => 'Syria', 'country_code' => '+963', 'iso_code' => 'SY'],
            ['country_name' => 'Taiwan', 'country_code' => '+886', 'iso_code' => 'TW'],
            ['country_name' => 'Tajikistan', 'country_code' => '+992', 'iso_code' => 'TJ'],
            ['country_name' => 'Tanzania', 'country_code' => '+255', 'iso_code' => 'TZ'],
            ['country_name' => 'Thailand', 'country_code' => '+66', 'iso_code' => 'TH'],
            ['country_name' => 'Timor-Leste', 'country_code' => '+670', 'iso_code' => 'TL'],
            ['country_name' => 'Togo', 'country_code' => '+228', 'iso_code' => 'TG'],
            ['country_name' => 'Tonga', 'country_code' => '+676', 'iso_code' => 'TO'],
            ['country_name' => 'Trinidad and Tobago', 'country_code' => '+1-868', 'iso_code' => 'TT'],
            ['country_name' => 'Tunisia', 'country_code' => '+216', 'iso_code' => 'TN'],
            ['country_name' => 'Turkey', 'country_code' => '+90', 'iso_code' => 'TR'],
            ['country_name' => 'Turkmenistan', 'country_code' => '+993', 'iso_code' => 'TM'],
            ['country_name' => 'Tuvalu', 'country_code' => '+688', 'iso_code' => 'TV'],
            ['country_name' => 'Uganda', 'country_code' => '+256', 'iso_code' => 'UG'],
            ['country_name' => 'Ukraine', 'country_code' => '+380', 'iso_code' => 'UA'],
            ['country_name' => 'United Arab Emirates', 'country_code' => '+971', 'iso_code' => 'AE'],
            ['country_name' => 'United Kingdom', 'country_code' => '+44', 'iso_code' => 'GB'],
            ['country_name' => 'United States', 'country_code' => '+1', 'iso_code' => 'US'],
            ['country_name' => 'Uruguay', 'country_code' => '+598', 'iso_code' => 'UY'],
            ['country_name' => 'Uzbekistan', 'country_code' => '+998', 'iso_code' => 'UZ'],
            ['country_name' => 'Vanuatu', 'country_code' => '+678', 'iso_code' => 'VU'],
            ['country_name' => 'Vatican City', 'country_code' => '+39', 'iso_code' => 'VA'],
            ['country_name' => 'Venezuela', 'country_code' => '+58', 'iso_code' => 'VE'],
            ['country_name' => 'Vietnam', 'country_code' => '+84', 'iso_code' => 'VN'],
            ['country_name' => 'Yemen', 'country_code' => '+967', 'iso_code' => 'YE'],
            ['country_name' => 'Zambia', 'country_code' => '+260', 'iso_code' => 'ZM'],
            ['country_name' => 'Zimbabwe', 'country_code' => '+263', 'iso_code' => 'ZW'],
        ];

        DB::table('country_codes')->insert($countryCodes);
    }
}
